# Generated by Django 5.0.4 on 2024-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamanho',
            name='adicional',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
