# Generated by Django 5.0.4 on 2024-05-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_tamanho_adicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='cor',
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='item_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produto'),
        ),
    ]
