# Generated by Django 5.0.4 on 2024-05-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_remove_itemestoque_cor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedido',
            old_name='item_estoque',
            new_name='produto',
        ),
    ]
