# Generated by Django 5.0.4 on 2024-05-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_rename_item_estoque_itenspedido_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cor',
        ),
        migrations.RemoveField(
            model_name='itenspedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itenspedido',
            name='produto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.tamanho'),
        ),
        migrations.DeleteModel(
            name='ItemEstoque',
        ),
        migrations.DeleteModel(
            name='ItensPedido',
        ),
    ]
