# Generated by Django 5.0.4 on 2024-05-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_delete_itenspedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='pedido',
            name='tamanho',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
