# Generated by Django 5.0.4 on 2024-05-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='adicheckaut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
