# Generated by Django 5.0.4 on 2024-05-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_pedido_adicheckaut_alter_pedido_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='adicheckaut',
            new_name='adicheckout',
        ),
    ]
