# Generated by Django 5.0.4 on 2024-06-02 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_remove_pedido_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.tamanho'),
        ),
    ]
