# Generated by Django 5.0.4 on 2024-06-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0021_pedido_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='adicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tamanho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
