# Generated by Django 5.0.4 on 2024-06-02 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0023_alter_pedido_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='adicional',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.tamanho'),
        ),
    ]
