# Generated by Django 5.0.4 on 2024-06-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0024_remove_pedido_adicional_alter_pedido_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tamanho',
        ),
    ]
