# Generated by Django 5.0.4 on 2024-06-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0026_pedido_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanho',
            name='nome',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
