# Generated by Django 5.0.4 on 2024-06-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0027_alter_tamanho_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tamanho',
        ),
    ]
