# Generated by Django 5.0.4 on 2024-06-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0032_endereco_telefone_alter_endereco_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
